# Generated by Django 4.2.7 on 2023-12-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('tags', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('hash_value', models.CharField(blank=True, max_length=32, null=True, unique=True)),
            ],
            options={
                'db_table': 'post',
                'managed': True,
            },
        ),
    ]
