# Generated by Django 4.2.7 on 2023-12-01 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('linesMan1', models.CharField(max_length=50)),
                ('linesMan2', models.CharField(max_length=50)),
                ('mainReferee', models.CharField(max_length=50)),
                ('seatPrice', models.IntegerField()),
                ('date', models.CharField(max_length=50)),
                ('hash_value', models.CharField(max_length=32)),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.stadium')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='game.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away', to='game.team')),
            ],
            options={
                'db_table': 'match',
                'managed': True,
            },
        ),
    ]
