# Generated by Django 4.2.7 on 2023-12-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='hash_value',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
