# Generated by Django 4.2.7 on 2023-12-01 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_match_hash_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadium',
            name='hash_value',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='hash_value',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
