# Generated by Django 4.2.7 on 2023-12-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_order_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadium',
            name='hash_value',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
